name: Report Checks

on:
  workflow_run:
    workflows: ['checks']
    types:
      - completed

permissions: read-all

jobs:
  report-missing-license-headers:
    permissions:
      checks: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Add step to download missing_license_headers artifact (details not provided)

      - name: Report missing headers
        run: ./contrib/scripts/report-license-headers.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_SHA: ${{ github.event.workflow_run.head_sha }}
        shell: bash

  report-clang-format-diff:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Add step to download artifact (details not provided)
      
      - name: Set PR Number environment variable
        run: echo "PR_NUMBER=$(cat pr_number/pr_number.txt | jq -r .)" >> $GITHUB_ENV
