name: Pull Request Created

on:
  pull_request:
    types:
      - opened

jobs:
  notify_and_setup_on_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Choose the desired Node.js version

      - name: Install npm dependencies
        run: npm install npm

      - name: Notify or Perform Action
        run: |
          # Add your notification or action logic here
          echo "A new pull request has been opened!"
