name: Echo on Pull Request

on:
  pull_request:
    types:
      - opened

jobs:
  echo_on_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Pull Request Message
        run: |
          echo "Hello there"
          echo "A new pull request has been created!"
          
